### ISSUE TITLE
Updated spanish.lua (Contribution)

### ISSUE THREAD

**Issue by gvaldebenit** [ONElua/AutoPlugin2#1]
Updated some loosy translation made on a PR on old repo. Also added some new tranlations and fixed some typos. 
Uploaded as .zip due to GitHub file upload restriction.
EDIT: Fixed a wrong language call

[SPANISH.zip](https://github.com/ONElua/AutoPlugin2/files/4276149/SPANISH.zip)

**Comment by ONElua** [comment]
Thanks
