### ISSUE TITLE
Vitacheat plugin missing .suprx and font

### ISSUE THREAD

**Issue by Yohoki** [ONElua/AutoPlugin2#10]
Installing Vitacheat (z06 for 3.65+) does not work as it is missing the font file.

For z06:
Requires .skprx, .suprx and font.dat
Link: https://github.com/r0ah/vitacheat/tree/master/plugin/v365-z06beta
font.dat goes in ux0:vitacheat/font/ . I've uploaded font.dat in a zip file here.

z06's description also says "Vitacheat Z06 BETA by r0ah FOR 3.65+" but r0ah is not the creator. Both were made by FinalCheat.
[font.zip](https://github.com/ONElua/AutoPlugin2/files/4283758/font.zip)

Edit: I just noticed that the plugin uses a "vitacheat.zip" file when installing either z06 or z05. The font file is actually inside that zip folder, which is fine, but they use different font files. They are not interchangeable.

https://github.com/ONElua/AutoPlugin2/blob/976655d674915a9800e6aac71f49efeae8d81ae3/AUTOPLUG2/scripts/psvita/autoplugin.lua#L214-L221

I would recommend removing the font file from the vitacheat.zip and having autoplugin only unpack the font file for z06. Z05 does not need a font.dat included, as it creates it's own if it does not exist. 
~~~~
				elseif plugins[sel].path == "vitacheat.skprx" then		--Vitacheat 3.65
					files.extract("resources/plugins/vitacheat.zip","ux0:")
					files.delete("ux0:/vitacheat/font/font.dat")		--Delete existing font.dat
					files.extract("resources/plugins/font.zip","ux0:/vitacheat/font")		--Font file for z06
					files.copy("resources/plugins/vitacheat365/vitacheat.suprx","ux0:vitacheat/")

				elseif plugins[sel].path == "vitacheat360.skprx" then	--Vitacheat 3.60

					files.extract("resources/plugins/vitacheat.zip","ux0:")
					files.delete("ux0:/vitacheat/font/font.dat")		--Delete existing font.dat
					files.copy("resources/plugins/vitacheat360/vitacheat.suprx","ux0:vitacheat/")
~~~~

**Comment by ONElua** [comment]
i test with font in both and working fine

**Comment by Yohoki** [comment]
hmmm. Not sure why people are saying it isn't working then. I'm afraid I don't use AutoPlugin, myself. But people are saying they're getting garbled text, which means that font.dat is currupt or missing. I'll get more info from them, or have them post here themselves.

**Comment by Yohoki** [comment]
I figured it out. It's a double install issue. If people manually installed vitacheat, and then updated with Autoplugin.

Instructions for vitacheat are to install the Kernel plugin to ur0:vitacheat/vitacheat.skprx, not ur:tai/vitacheat.skprx . So, if a user installed a version manually, then used autoplugin to install another version, there will be 2 versions running at once. So, it's partially user error and partially Autoplugin using different install methods.

I'll update the vitacheat install to install into tai folder instead of ur0:vitacheat/

**Comment by ONElua** [comment]
> I'll update the vitacheat instructions on r0ah's github to install into tai folder instead of ur0:vitacheat/

thanks

**Comment by ONElua** [comment]
This its for 3.60 ??
https://github.com/r0ah/vitacheat/tree/master/plugin/v360-z04beta

or 
https://github.com/r0ah/vitacheat/tree/master/plugin/v365-z05beta
