### ISSUE TITLE
Fix Sharpscale Config Crash

### ISSUE THREAD

**Issue by Codemonkey03** [ONElua/AutoPlugin2#100]
I accidentally closed my own topic I think? My apologies. 

In reference to this thread.
https://github.com/ONElua/AutoPlugin2/issues/99

And my reply to the last post:

Everytime. My original config is:
https://pastebin.com/rJprgAY3

And I followed along with the config posted in the closed thread that resolved the issue for another ticket and now it looks like this cleaned up:
https://pastebin.com/td65hfDt

Same issue though, get the message every time Autoplugin boots even though all my plugins are operating normally. Everytime I open Autoplugin, get the error and it restarts it adds another !AKRK00005 to the config. This happened a dozen times without me noticing in the original config.

I'm not sure what the message is doing, could it perhaps just be disabled in the next Autoplugin update?

**Comment by ONElua** [comment]
Please try with this config
[config.zip](https://github.com/ONElua/AutoPlugin2/files/5455658/config.zip)

**Comment by Codemonkey03** [comment]
> Please try with this config
> [config.zip](https://github.com/ONElua/AutoPlugin2/files/5455658/config.zip)

That worked. No error message. What was changed to make it work? 

Thank you for the help.

**Comment by ONElua** [comment]
I'm checking to fix it completely

**Comment by ONElua** [comment]
Fix
https://github.com/ONElua/AutoPlugin2/commit/8a391e0338b18df4e421ff13c9139ae82dbb7be5
