### ISSUE TITLE
not able to update to Autoplugin v1.16

### ISSUE THREAD

**Issue by hossbags2** [ONElua/AutoPlugin2#105]
I was able to update PSVITA TV to 1.16 with no problem. My handheld PSVITA is stuck in a loop. It downloads with no problem. Whil unpacking, it reloads Autoplugin 1.15 and asks to download again then while unpacking, it starts over again

**Comment by ONElua** [comment]
Do you have the white bubble updater?

**Comment by hossbags2** [comment]
I have the bubble updater on home screen.....yea

**Comment by ONElua** [comment]
please 
uninstall
and try

**Comment by hossbags2** [comment]
where do I download it from again....also will i need to install my plugins again

**Comment by ONElua** [comment]
unnistall only bubble updater (White bubble)
not autoplugin2

**Comment by ONElua** [comment]
https://github.com/ONElua/AutoPlugin2/releases/tag/1.16
or reinstall v1.16

**Comment by hossbags2** [comment]
what I have is the autoplugin 2 bubble

**Comment by hossbags2** [comment]
I dont have the bubble updater....have not done anything yet....and thanks for your help

**Comment by ONElua** [comment]
Fixed?

**Comment by hossbags2** [comment]
no...not yet. I dont have the bubble updater.....I should be able just  to reinstall  Autoplugin overtop of what is there....what about the plugins

**Comment by hossbags2** [comment]
I have not done anything yet so you know

**Comment by ONElua** [comment]
only reinstall autoplugin2
https://github.com/ONElua/AutoPlugin2/releases/tag/1.16

Your plugins stay without changes

**Comment by BaltazaR4** [comment]
Hello hossbags2, don't worry about the plugins already installed in your ps vita, just uninstall v1.15 and download v1.16 and install it with vitashell or Onemenu

**Comment by hossbags2** [comment]
I will try a little later and let you know the outcome........thanks...........can I just intall 1.16 on top of 15 without uninstalling or deleting the autoplugin bubble........main thing is I dont want to mess it up and thanks

**Comment by BaltazaR4** [comment]
You can do so if you like, please let us know if any other issue comes up
