### ISSUE TITLE
bad argument

### ISSUE THREAD

**Issue by WHATADAMNHOTDAY** [ONElua/AutoPlugin2#11]
bad argument#2 to format (string expected, got nil) this showed up when i open 

ps i'm not uninstall autoplugin1 is that is a problem？

**Comment by WHATADAMNHOTDAY** [comment]
![image](https://user-images.githubusercontent.com/14843555/75918730-3a55de00-5e97-11ea-9d31-bd510aebb11a.jpg)
while i open the app

**Comment by ONElua** [comment]
You're translating ???
Missing string

**Comment by WHATADAMNHOTDAY** [comment]
sry i mean when I open the autoplugin2, it becomes as shown in the pic

**Comment by BaltazaR4** [comment]
WHATADAMNHOTDAY can you tell us the system language set in your ps vita please?

**Comment by WHATADAMNHOTDAY** [comment]
> WHATADAMNHOTDAY can you tell us the system language set in your ps vita please?

 traditional Chinese

**Comment by BaltazaR4** [comment]
Try changing to english and then open Autoplugin2 go to its settings, select change language, then select chinese and Autoplugin2 will download a pgf font file and thats it.

**Comment by WHATADAMNHOTDAY** [comment]
> Try changing to english and then open Autoplugin2 go to its settings, select change language, then select chinese and Autoplugin2 will download a pgf font file and thats it.

thanks！！！！！
