### ISSUE TITLE
Plugins manager in PSP (Adrenaline) Plugins duplicates existing plugins

### ISSUE THREAD

**Issue by GameSpiritGS** [ONElua/AutoPlugin2#111]
Everytime I open it, they get duplicated, list expands.

**Comment by ONElua** [comment]
Please send me screenshots and your vsh.txt or game.txt

**Comment by GameSpiritGS** [comment]
uploaded a short video instead of screenshots https://www.youtube.com/watch?v=ZrUPhYhRCF8

vsh.txt and game.txt both has only one line
ms0:/seplugins/npdrm_free.prx 1

turns to normal after restarting app

**Comment by ONElua** [comment]
Please try
https://www.dropbox.com/s/gnz2zaopjctglm6/AutoPlugin2.vpk?dl=0

https://github.com/ONElua/AutoPlugin2/commit/d79674e90d74707a00f4c33e53302b3b6a87de6a
https://github.com/ONElua/AutoPlugin2/commit/8164dc4198cfa31241e099bc4cd789ab778b0b4a

**Comment by GameSpiritGS** [comment]
Solved! Thanks. It was only visual but I wanted to report.
