### ISSUE TITLE
error question

### ISSUE THREAD

**Issue by Honeylife77** [ONElua/AutoPlugin2#112]
app version v1.18

Few days ago, When i update plugin,

"Error decoding Langdatabase
 Internet is required"

Pop-up is coming up

Wifi is not problem
Another app is noproblem internet (ex. pkgj)

**Comment by ss9918** [comment]
same issue here

**Comment by RobZombie9043** [comment]
Same issue as well, wifi working for everything else. Was on 1.13 and updated to 1.18 and same on both versions.

**Comment by ONElua** [comment]
Region? Country?

**Comment by ss9918** [comment]
East coast in USA I figured server down maybe?


Sent from Yahoo Mail for iPhone


On Saturday, January 16, 2021, 7:09 PM, ONELua Team <notifications@github.com> wrote:




Region? Country?

**Comment by ONElua** [comment]
Download iTLS-enso.vpk by SKGleba using Autoplugin2 and install the full iTLS package

**Comment by RobZombie9043** [comment]
Thanks, that worked

**Comment by Honeylife77** [comment]
> Download iTLS-enso.vpk by SKGleba using Autoplugin2 and install the full iTLS package

Already install iTLS-ENSO 3.1 and Full package install but still have same error

**Comment by Honeylife77** [comment]
> Region?
> Country?
> Language?

Region is ASIA
Country is South Korea
Language is English

**Comment by ONElua** [comment]
@Honeylife77 versión? You hace AP2 v1.19?

**Comment by Honeylife77** [comment]
> @Honeylife77
> Ofw version ?
> 
> You hace AP2 v1.19?
> Restart your Vita?

I use 3.65 ENSO
Restat already
You hace AP2 v1.19? -> No i don't

I think my vita is noproblem
because before i can update plugin 
after nothing chage

but i can't update now

**Comment by ONElua** [comment]
https://github.com/ONElua/AutoPlugin2/releases/tag/1.19

**Comment by Masters110** [comment]
> Download iTLS-enso.vpk by SKGleba using Autoplugin2 and install the full iTLS package

Thanks  working again
