### ISSUE TITLE
AutoPlugin II v1.20 - error updating plugins or app

### ISSUE THREAD

**Issue by tatundria** [ONElua/AutoPlugin2#116]
It gives me .lua error while trying to update either plugins or the app with AutoPlugin II latest version (v1.20)

**Comment by ONElua** [comment]
Fix (Update for plugins
https://github.com/ONElua/AutoPlugin2/commit/67e2a25d5ef82b1f2fe7b0ed6cae77a78ab2cc25
Please try!!


For update v1.19 to 1.20
download and install manually
https://github.com/ONElua/AutoPlugin2/releases/tag/1.20

**Comment by tatundria** [comment]
Working now. Thanks!

**Comment by ONElua** [comment]
V1.21 is out!!!
