### ISSUE TITLE
AutoPlugin2  V1.20 - Plugins UPDATE ERROR! Need Fix 

### ISSUE THREAD

**Issue by PhilRoll** [ONElua/AutoPlugin2#117]
Last 1.20version gives this error if i try to update plugins:

dir:        ux0:/app/AUTOPLUG2/scripts/psvita/plugins_online.lua
file:       plugins_online.lua (line 158)
error:    attempt to get length of global 'Online_Plugins' (a nil value)

Plz fix it! Thanks

**Comment by renatotec** [comment]
Same here.

**Comment by realNZZN** [comment]
Looks like it's happening to everyone

**Comment by ONElua** [comment]
Fix
https://github.com/ONElua/AutoPlugin2/commit/67e2a25d5ef82b1f2fe7b0ed6cae77a78ab2cc25
Please try!!
