### ISSUE TITLE
Updating from 1.19 to 1.20 or 1.21 get this needs fixing

### ISSUE THREAD

**Issue by Shadow322** [ONElua/AutoPlugin2#120]
![2021-01-25-192815-633193](https://user-images.githubusercontent.com/15938645/105787079-db340880-5f43-11eb-8b1c-610998f0e0d9.png)

**Comment by Masamune3210** [comment]
Manually update using the vpk, there is a known issue updating to the latest version from an older one sometimes

**Comment by ONElua** [comment]
https://github.com/ONElua/AutoPlugin2/issues/116#issuecomment-767133513
