### ISSUE TITLE
Improvement: add a note about pluginless boot

### ISSUE THREAD

**Issue by Yoti** [ONElua/AutoPlugin2#139]
It will be great to add note about pluginless boot (hold L while booting enso enabled console or when running an h-encore) to this screen:
![2021-03-17-194641](https://user-images.githubusercontent.com/1880088/111506476-b77a8b00-875a-11eb-81af-2865c1e6a28b.jpg)
Because if you broke your Vita with incompatible plugins you will know how to fix.

**Comment by ONElua** [comment]
Done!
These changes will take effect until the next update.
