### ISSUE TITLE
Having trouble with CXMB plugin installed using Autoplugin

### ISSUE THREAD

**Issue by dothackjhe** [ONElua/AutoPlugin2#140]
Not sure if the issue was caused by installing CXMB via Autoplugin, but I began having an issue with it after impulsively installing the plugin on top of my pre-existing (manually-configured). Now, I'm having trouble not being able to use a custom theme, and I noticed that the contents within the pspemu/PSP/THEME get auto-deleted every time after running Adrenaline-7.

**Comment by ONElua** [comment]
adrenaline v7 or mod ??

**Comment by dothackjhe** [comment]
v7, I think.

**Comment by ONElua** [comment]
please show me your vsh.txt and your ctf (pspemu/PSP/THEME)

**Comment by dothackjhe** [comment]
Here's a compilation of the several custom themes I was using: https://www.mediafire.com/file/qosp42ysh5d8hzs/CTFClearXMBCollection661CFPlus.rar/file

As for the VSH configuration: 
ms0:/seplugins/npdrm_free.prx 1
ms0:/seplugins/category_lite.prx 1
ms0:/cxmb/cxmb.prx 1

**Comment by ONElua** [comment]
cmbx and theme.ctf 
it's in the same partition?

**Comment by dothackjhe** [comment]
Yes.

I recall the original configuration being different, though. But after having deleted the said setting and letting Autoplugin do the plugin, that's now how it looks like.

**Comment by BaltazaR4** [comment]
Have you tried other themes? I tried the pack from your link and none of them worked, I even delete the cxmb setup installed by Autoplugin 2 and installed everything manually and, sorry to tell you this, but the themes in the link you shared, none of them worked with the manual setup either, try with this one http://www.pspthemecentral.com/download/jumbled660.zip

**Comment by dothackjhe** [comment]
So, it's the CTF files that are faulty, then? 

I'll see if other custom themes will work.

**Comment by BaltazaR4** [comment]
I tried with the ctf themes from the link you provided but none of them worked, tried the one of the link in my comment and that one worked with the $ony logo disbled

**Comment by dothackjhe** [comment]
I tried a different theme (Metal Gear Solid one), but it, too, would not work. Like previously, it gets auto-deleted from the THEME folder as well.

**Comment by ONElua** [comment]
@dothackjhe Intentaste con este
http://www.pspthemecentral.com/download/jumbled660.zip
