### ISSUE TITLE
Remove Lolicon

### ISSUE THREAD

**Issue by SomeonPC** [ONElua/AutoPlugin2#146]
Please remove Lolicon, Its the bane of our existence in the hacking community. Even just make it pop up a warning on attempt to install and recommend the install of PSVShell.

**Comment by bielgiroto** [comment]
I agree with him, Lolicon has a weird name and it's obsollete at this point, PSVshell supports 720p res now and there's no real reason to use it in the place of PSVshell

**Comment by ONElua** [comment]
And Lolita?

**Comment by bielgiroto** [comment]
Nah, Lolita probably it's a good feature for PSTV users, I think it's ok keeping them.

Some people use it on regular Vitas as well, I think only Lolicon should be removed.

Also, Lolita444 and Lolita500 work great, and have less cringe names than Lolicon.

**Comment by ONElua** [comment]
ok
