### ISSUE TITLE
Add new (maybe more) vpk and plugin (if i can find one) in Autoplugin II (Suggestion's for the next or Future Update's)

### ISSUE THREAD

**Issue by hedhehd** [ONElua/AutoPlugin2#154]
https://bitbucket.org/SilicaAndPina/fastreset/src/master/
Option name:Download and install fastreset vpk 2.0 by SilicaAndPina

**Comment by hedhehd** [comment]
Propably more vpks or plugins will be suggested.

**Comment by hedhehd** [comment]
Other people can also suggest not only me.

**Comment by hedhehd** [comment]
This issue (Suggestion) will be never closed until the new Autoplugin III or something comes.

**Comment by hedhehd** [comment]
I'm gonna make a new issue (Suggestion) on Autoplugin III when it comes and close this.

**Comment by hedhehd** [comment]
I have a new splash.png.
![splash](https://user-images.githubusercontent.com/81228260/123450129-ac968880-d5dc-11eb-9507-1a65427ff4b8.png)

**Comment by hedhehd** [comment]
sorry if its not the right bit

**Comment by hedhehd** [comment]
here is the right one.
![pic0](https://user-images.githubusercontent.com/81228260/123470424-af04dc80-d5f4-11eb-9ed4-24d7c8a5bbdc.png)

**Comment by ONElua** [comment]
Thanks xD
I'm working on it

**Comment by hedhehd** [comment]
I made a Redesign of AutoPlugin II too the whole thing is changed but its not really a Redesign because i copyed some .png files to replace some in "img" folder (Example back.png)
![back](https://user-images.githubusercontent.com/81228260/123541330-3d3ba880-d744-11eb-89e8-49acf7252b7b.png)

**Comment by hedhehd** [comment]
Theres my link to it https://github.com/hedhehd/AutoPlugin2-Redesign

**Comment by hedhehd** [comment]
but it doesnt look that bad though

**Comment by hedhehd** [comment]
also the icon0.png looks not simillar and its completely different
![icon0](https://user-images.githubusercontent.com/81228260/123541433-e1bdea80-d744-11eb-8f40-3998da754222.png)

**Comment by hedhehd** [comment]
not really but... yeah xD

**Comment by hedhehd** [comment]
The source file is messed up i forgot to make AUTOPLUG2 Folder and put stuff in it xD

**Comment by hedhehd** [comment]
I always wondered how to add plugins maybe edit the plugins.lua and put the plugin in the resource folder then plugins ps vita?

**Comment by hedhehd** [comment]
also the vpks

**Comment by ONElua** [comment]
Im working in a new update (but it will take a long time)

**Comment by hedhehd** [comment]
Ok i already saw reAuth get added and more. That was fast though.
