### ISSUE TITLE
add reauth?

### ISSUE THREAD

**Issue by Masamune3210** [ONElua/AutoPlugin2#155]
Could we get reauth added to autoplugin? Its required from now on for anyone under 3.68 to sign in to PSN successfully so would be nice for it to be easier to get

**Comment by hedhehd** [comment]
That's a... great idea. I would like to add the new version of AutoPlugin II (2) Redesign by me.

**Comment by Masamune3210** [comment]
Its not as big of a deal as I originally thought as the fix is also included in iTLS but still would be nice

**Comment by hedhehd** [comment]
I also already h͟a͟v͟e͟ reauth in my Vita. So i don't need to install it again

**Comment by ONElua** [comment]
Added
