### ISSUE TITLE
Autoplugin2 crashes on start

### ISSUE THREAD

**Issue by marcosbong73** [ONElua/AutoPlugin2#160]
Autoplugin2 crashes on start.
Error code C2-12828-1
Enso installed
Firmware version 3.60
Spoofing firmware vers 3.73
Unsafe homebrews activated
Only one tai folder in ur0
No SD2vita adapter
Tested versions:
1.25 1.24 1.22 1.18

**Comment by ONElua** [comment]
Maybe pmugkn

**Comment by marcosbong73** [comment]
> Maybe plugins conflict

No plugins installed manually by my own

tai folder content:

boot_config.txt
config.txt
henkaku.skprx
henkaku.suprx
henkaku_config.bin
taihen.skprx

**Comment by ONElua** [comment]
Show me yoir  config.txt

**Comment by marcosbong73** [comment]
# This file is used as an alternative if ux0:tai/config.txt is not found.
# For users plugins, you must refresh taiHEN from HENkaku Settings for
# changes to take place.
# For kernel plugins, you must reboot for changes to take place.
*KERNEL
ux0:tai/kubridge.skprx
# henkaku.skprx is hard-coded to load and is not listed here
*main
# main is a special titleid for SceShell
ur0:tai/henkaku.suprx
*NPXS10015
# this is for modifying the version string
ur0:tai/henkaku.suprx
*NPXS10016
# this is for modifying the version string in settings widget
ur0:tai/henkaku.suprx

**Comment by hedhehd** [comment]
Ermmm you have Kubridge.. but theres no kubridge.skprx?

**Comment by ONElua** [comment]
Kubridge in ux0?

**Comment by hedhehd** [comment]
Oh. Didn't see that

**Comment by vkay94** [comment]
I'm facing the same problem and I have the same system configuration in the OP. The only plugin is Adrealine v5.1 . The following error message s shown when starting AutoPlugin II:

```
An error has occurred in the following application. (C2-12828-1)
Saved Core File Succeeded.
ux0:data/psp2core-1632143270-[some long hash]-eboot.bin.psp2dmp
```

The contents of the `config.txt` file in `ux0:tai`:

```
# You must reboot for changes to take place.
# henkaku.suprx and henkaku.skprx has moved to ur0:tai, you may remove
# the old entries above.
*KERNEL
ux0:adrenaline/adrenaline.skprx
# henkaku.skprx is hard-coded to load and is not listed here
*main
# main is a special titleid for SceShell
ur0:tai/henkaku.suprx
*NPXS10015
# this is for modifying the version string
ur0:tai/henkaku.suprx
*NPXS10016
# this is for modifying the version string in settings widget
ur0:tai/henkaku.suprx
*NPEZ00104
ux0:adrenaline/adrenaline.suprx
```

**Comment by ONElua** [comment]
why?
npez00104
.... adrenaline. suprx

**Comment by ONElua** [comment]
@vkay94
why?
npez00104
.... adrenaline. suprx

**Comment by vkay94** [comment]
That's the ID of the Mini game which is used by AdrealineEasyInstaller I think.

Yeah, the contents of `ur0:tai/config.txt`:
```
# This file is used as an alternative if ux0:tai/config.txt is not found.
# For users plugins, you must refresh taiHEN from HENkaku Settings for
# changes to take place.
# For kernel plugins, you must reboot for changes to take place.
*KERNEL
# henkaku.skprx is hard-coded to load and is not listed here
*main
# main is a special titleid for SceShell
ur0:tai/henkaku.suprx
*NPXS10015
# this is for modifying the version string
ur0:tai/henkaku.suprx
*NPXS10016
# this is for modifying the version string in settings widget
ur0:tai/henkaku.suprx
```

(I didn't post it because it's stated that it's ignored  :'))

**Comment by vkay94** [comment]
Nevermind, the bug has disappeared when I've switched from 3.60 enso installed the CFW via VitaDeploy 👍

**Comment by marcosbong73** [comment]
Hi again
Cleaning dust from my old PS Vita.
Error persist.
My config.txt

# This file is used as an alternative if ux0:tai/config.txt is not found.
# For users plugins, you must refresh taiHEN from HENkaku Settings for
# changes to take place.
# For kernel plugins, you must reboot for changes to take place.
*KERNEL
# henkaku.skprx is hard-coded to load and is not listed here
*main
# main is a special titleid for SceShell
*NPXS10015
# this is for modifying the version string
ur0:tai/henkaku.suprx
*NPXS10016
# this is for modifying the version string in settings widget
ur0:tai/henkaku.suprx
