### ISSUE TITLE
3.60 vitacheat invalied font

### ISSUE THREAD

**Issue by wzhy90** [ONElua/AutoPlugin2#164]
Since 3.60 only has z50 vitacheat, and this version use another font file, it just 196KB. ATM the 16MB font is for z60, if you use 16mb font in z50, the Chinese character will be broken. Here is the right font for z50 and below
[font.zip](https://github.com/ONElua/AutoPlugin2/files/7454713/font.zip)

**Comment by ONElua** [comment]
https://github.com/ONElua/AutoPlugin2/issues/10
