### ISSUE TITLE
Add QuickLauncher and QuickMenuReborn

### ISSUE THREAD

**Issue by takoyaki99** [ONElua/AutoPlugin2#166]
These plugins allow games and bubbles to be launched from the quick menu. Similar to this [https://github.com/theheroGAC/QuickLaunch_installer_for_PSVita](url) but for the quick menu.
Here are the links to both plugins (QuickLauncher is dependent on QuickMenuReborn to run)
[https://github.com/Ibrahim778/QuickLauncher](url)
[https://github.com/Ibrahim778/QuickMenuReborn](url)
Thank you for your time!!

**Comment by ONElua** [comment]
Hi...
Thanks
I'm testing
![QuickMenuLauncher](https://user-images.githubusercontent.com/25811032/149680311-2165eb62-bb86-4434-b758-b3b3215898b4.jpg)

**Comment by ONElua** [comment]
https://github.com/ONElua/AutoPlugin2/releases/tag/1.26
