### ISSUE TITLE
Can't access to autoplugin2 when using Traditional Chinese as system language

### ISSUE THREAD

**Issue by PaulLee44** [ONElua/AutoPlugin2#17]
I am taiwanese and my vita system language is Traditional Chinese, when access to autoplugin2, screen change to bug collecting screen and said script.lua line:57 have issue with *attempt to call global" message..."*(sorry for I forget more about this issues information since I find a way to fix this problem).

My way to fix this problem(system language is Traditional Chinese):
1. change your system language to English(us) to access autoplugin 2 without problem.
2. go to settings and change language to Chinese_S.
3.change vita system language back to Traditional Chinese.
4. now can access autoplugin 2 without have problem.

Hope you team can fix this problem, Thanks!

**Comment by Yoti** [comment]
Program has on start font check for selected languages. Maybe you don't have active Internet connection on first start?

https://github.com/ONElua/AutoPlugin2/blob/master/AUTOPLUG2/script.lua#L55

**Comment by PaulLee44** [comment]
I am pretty sure my vita have connect to Internet, because after I can access to autoplugin2 and change language to Chinese_S, there were a bar below said downloading Chinese_S font.

**Comment by yexun1995** [comment]
There are currently no Chinese_T language files for the APII project.Perhaps creating it will solve this problem.

**Comment by PaulLee44** [comment]
@yexun1995 maybe just make APII default language as Chinese_S when system is Chinese_T or Chinese_S ? 
Or translate Chinese_S to Chinese_T(translate font is easy but I don't know how to make it to a file)?

**Comment by ONElua** [comment]
Yes

download the font manually and place in ux0:data /autoplugin2/font
https://github.com/ONElua/AutoPlugin2/blob/master/font/font.pgf

fix in the next version....

**Comment by PaulLee44** [comment]
@ONElua Ok,thanks!!
