### ISSUE TITLE
add PasteUnlock

### ISSUE THREAD

**Issue by KuromeSan** [ONElua/AutoPlugin2#170]
Seems like a cool plugin https://forum.devchroma.nl/index.php/topic,376.0.html

**Comment by hedhehd** [comment]
I can do it in here https://github.com/hedhehd/AutoPlugin2-Redesign

**Comment by ONElua** [comment]
> Seems like a cool plugin https://forum.devchroma.nl/index.php/topic,376.0.html

https://github.com/ONElua/AutoPlugin2/commit/36b8bf40eb2a4c711f4d456eafe4dfaca3ce2737
