### ISSUE TITLE
New plugin: PocketStation Unlocker

### ISSUE THREAD

**Issue by Yoti** [ONElua/AutoPlugin2#171]
https://silica.codes/SilicaAndPina/PocketstationUnlocker/releases

**Comment by BaltazaR4** [comment]
Hello, is this plugin compatible with adrenaline?
If you already tried it, can you mention the game please? Thanks in advance

**Comment by Yoti** [comment]
@BaltazaR4 as I know this plugin is for legit games.

**Comment by BaltazaR4** [comment]
Ok, thanks for the info

**Comment by ONElua** [comment]
Thanks 👍 

https://github.com/ONElua/AutoPlugin2/commit/871dc73709c2b0593c98ce6eeeb0a07e424714a4#diff-1fbe60798fc2ec72487fdff95f1184fbf1927934124d6a2d2874bef0d7e483fc
