### ISSUE TITLE
I'm having trouble making the plugins updater to locate on my web.

### ISSUE THREAD

**Issue by hedhehd** [ONElua/AutoPlugin2#173]
ux0:/app/AUTOPLUG2/scripts/psvita/plugins_online,lua
Line:160
Problem:attempt to get length of global "Online_Plugins" (a nil value)

Could you please check the code on my repo?
https://github.com/hedhehd/Autoplugin2-Remaster/

**Comment by hedhehd** [comment]
I invited you for accsess on my Repo

**Comment by hedhehd** [comment]
I'm having also trouble with every updater. The plugin updater does not work. The AutoPlugin updater does not work.

**Comment by ONElua** [comment]
https://github.com/hedhehd/AutoPlugin2-Remaster/commit/ad034e3dfeb6c9ba5e4aa138f466e874a2ce365e

**Comment by hedhehd** [comment]
> [hedhehd/AutoPlugin2-Remaster@ad034e3](https://github.com/hedhehd/AutoPlugin2-Remaster/commit/ad034e3dfeb6c9ba5e4aa138f466e874a2ce365e)

One more problem is that I tried making the AutoPlugin II updater to check on my updates. But as you know. It doesn't work
