### ISSUE TITLE
Revita plugin file from autoplugin 2 is incorrect and different from authors' github release

### ISSUE THREAD

**Issue by Jimmisama** [ONElua/AutoPlugin2#175]
https://github.com/MERLev/reVita/issues/43

The plugin version is 1.0.8 and it shows in the configuration menu, so that's correct. Howerver when I close the configuration menu, my psvita crashes. Also I cannot boot if I install the revitamotion plugin too.

And I finally found out, the revitamotion, ds34vita plugin are all exactly the same size as the one from MERLev's github page. The revita plugin however, is only about 50kb in size while the one from MerLev's Github is about 80kb. After replacing the plugin file from the official github page, everything works fine again.

I have autoplugin 2 installed and my system is on 3.65 Enso

**Comment by ONElua** [comment]
Ok
V1.07 is in AP2
Im upload V1.08

**Comment by Jimmisama** [comment]
> Ok
> V1.07 is in AP2
> Im upload V1.08

Thanks for continuous support of the autoplugin 2. However, if I remember correctly (maybe not), it showed 1.0.8 when pressing START + SQAURE too. Anyway it doesn't matter if it's fixed.

**Comment by ONElua** [comment]
Please Try
Check for plugins updates

**Comment by Jimmisama** [comment]
Well first of all, I lived at a place where network connections to foreign servers are very very unstable. So that's the major reason for sure.  
I tried for half a day and finally connected to the server ( I suppose). Two plugins were updated. One is something like pocketstationxxxx, can't really remember, another one is revita. Since I've already replaced revita manually so no updates available next time I've checked successfully no updates available.

Anyway, any optimization that could be done for poor network connections like me? The following happens too often.
![2022-08-01-143242-441013](https://user-images.githubusercontent.com/30177832/182097703-02ee4321-4f35-404c-af49-0ed766b45feb.png)
And after I click the update:
![2022-08-01-143247-163820](https://user-images.githubusercontent.com/30177832/182097507-da3964fd-b661-4648-ab16-10463604875b.png)
Sometimes after clicking check for plugin updates, it just stays at please wair, forever, and I have to reboot becuase the PlayStation button stopped working

**Comment by hedhehd** [comment]
> "attempt to get length of global ´Online_Langs´ (a nil value)

I don't think that issue is happening to me... is it? Or is it related to my issue I had?

**Comment by hedhehd** [comment]
I have no idea how to fix that. The best is to wait for ONELua to answer

**Comment by hedhehd** [comment]
Wait can you show this without it blocked by that annoying message? 
![image](https://user-images.githubusercontent.com/81228260/182129172-d85e9e58-f74f-4cbe-abe1-f613a291e3f9.png)

**Comment by hedhehd** [comment]
Then I can see where the problem occours.

**Comment by ONElua** [comment]
> Well first of all, I lived at a place where network connections to foreign servers are very very unstable. So that's the major reason for sure. I tried for half a day and finally connected to the server ( I suppose). Two plugins were updated. One is something like pocketstationxxxx, can't really remember, another one is revita. Since I've already replaced revita manually so no updates available next time I've checked successfully no updates available.
> 
> Anyway, any optimization that could be done for poor network connections like me? The following happens too often. ![2022-08-01-143242-441013](https://user-images.githubusercontent.com/30177832/182097703-02ee4321-4f35-404c-af49-0ed766b45feb.png) And after I click the update: ![2022-08-01-143247-163820](https://user-images.githubusercontent.com/30177832/182097507-da3964fd-b661-4648-ab16-10463604875b.png) Sometimes after clicking check for plugin updates, it just stays at please wair, forever, and I have to reboot becuase the PlayStation button stopped working

Please install
[AP2](https://www.mediafire.com/file/4f6rxl4vx2f8iaj/AP2_test.vpk/file)

and show


![IMG-20220801-WA0014](https://user-images.githubusercontent.com/25811032/182274975-e74de51d-6b7c-48f3-af04-b8f6db0ebd74.jpeg)
![IMG-20220801-WA0018](https://user-images.githubusercontent.com/25811032/182275002-f8dec31e-3cbd-462e-b8b3-e43debbb1979.jpeg)
