### ISSUE TITLE
[plugin update] StorageMgr v3.4 (by CelesteBlue & Yoti)

### ISSUE THREAD

**Issue by Yoti** [ONElua/AutoPlugin2#176]
New: https://github.com/RealYoti/StorageMgr/releases/tag/v3.4
Old: https://github.com/ONElua/AutoPlugin2/blob/master/AUTOPLUG2/resources/plugins/storagemgr.skprx
Fix1: https://github.com/ONElua/AutoPlugin2/blob/master/AUTOPLUG2/lang/ENGLISH_US.lua#L33
Fix2: https://github.com/ONElua/AutoPlugin2/blob/master/AUTOPLUG2/lang/ENGLISH_US.lua#L34

**Comment by ONElua** [comment]
https://github.com/ONElua/AutoPlugin2/commit/8e1bcb4eff4520728be70ffdda2d85ad857f98b1
