### ISSUE TITLE
Add hide-autoplugin plugin

### ISSUE THREAD

**Issue by KuromeSan** [ONElua/AutoPlugin2#181]
This plugin shouldnt be needed. But apparently it is. 

https://silica.codes/SilicaAndPina/hide-autoplugin/releases

**Comment by hedhehd** [comment]
Honestly, it is hilarious that it is for autoplugin and you install it from autoplugin.
lol

**Comment by ONElua** [comment]
https://github.com/ONElua/AutoPlugin2/commit/f90ad79aae1be8af37c91ecb711387706e08e426

**Comment by ONElua** [comment]
Extra configuration
*!VITASHELL
*!1MENUVITA

**Comment by ONElua** [comment]
there's no need
