### ISSUE TITLE
Update PocketStationUnlocker by Li

### ISSUE THREAD

**Issue by KuromeSan** [ONElua/AutoPlugin2#188]
https://silica.codes/SilicaAndPina/PocketstationUnlocker/releases it got update

**Comment by ONElua** [comment]
https://github.com/ONElua/AutoPlugin2/commit/6878a1a6be145fe13d9c2d6cb6b1e2e789f4d058

**Comment by ONElua** [comment]
Where is version 1.1? :(

**Comment by LiEnby** [comment]
wait what the .. sorry but i have no idea, (i don't even remember making this issue either-)

**Comment by LiEnby** [comment]
<img width="879" height="503" alt="Image" src="https://github.com/user-attachments/assets/54c88012-d0b6-433a-bda9-dd83ddb7270c" />

its possibly this commit, but it seems never uploaded a release with it :?

**Comment by LiEnby** [comment]
<img width="1134" height="273" alt="Image" src="https://github.com/user-attachments/assets/8e074a73-088b-41f6-aa87-f1b6c1a7bd16" />actually something shows up if im signed in xS ig i never published it properly

**Comment by LiEnby** [comment]
ok well i made a public 1.1 i guess; sorry ..

**Comment by ONElua** [comment]
:D Thanks!!!!!
