### ISSUE TITLE
LCD colour by cuevavirus says I don't have vita 2000 but I have

### ISSUE THREAD

**Issue by pitrako** [ONElua/AutoPlugin2#189]
This plugin keeps saying I'm not using a vita slim but It isn't true (says It's only compatible with 2000 vitas), If I use registry editor I can change to "oled emulation mode" and put pspemu-colour-crunch.skprx manually then It says It's installed in autoplugin 2 with a green mark, but I can't install It automatically from autoplugin.

**Comment by ONElua** [comment]
Your vita is fat?

**Comment by pitrako** [comment]
It's slim but autoplugin says It's fat.

**Comment by pitrako** [comment]
![IMG_20220914_003931](https://user-images.githubusercontent.com/42267151/190022028-df9866b0-83dd-4fea-8fbb-5782255ba5ee.jpg)

**Comment by ONElua** [comment]
Only for you
Please add --
https://github.com/ONElua/AutoPlugin2/blob/master/AUTOPLUG2/scripts/psvita/autoplugin.lua#L20
In your script "autoplugin.lua"

**Comment by ONElua** [comment]
Replace
[bin](https://www.dropbox.com/s/46t74rhxdfct05s/eboot.bin?dl=0)

**Comment by pitrako** [comment]
It works.

**Comment by ONElua** [comment]
Please try again 
https://github.com/ONElua/AutoPlugin2/releases/tag/1.28

**Comment by pitrako** [comment]
I installed the 1.28 update, uninstalled the plugin, installed It again and works.

**Comment by ONElua** [comment]
Ok
