### ISSUE TITLE
it is always necessary to stay connected to the internet to install any plugin.

### ISSUE THREAD

**Issue by JaegerFox** [ONElua/AutoPlugin2#193]
autoplugin is an app for the simple installation of plugins, where you have a local repository of plugins but in the last update for the installation of any plugin is necessary to have internet to view the readme that is downloaded and that causes the script to crash if you have the wifi disabled, this latest update I feel that ruined several things.
I back to the previous version...

**Comment by ONElua** [comment]
Yes
https://github.com/ONElua/AutoPlugin2/commit/1eeef66ee00be8fb3bccc153db9c2c8c401c1ac3
