### ISSUE TITLE
MiniVitaTV has beta 5 and this is still 4

### ISSUE THREAD

**Issue by UnLuck3R** [ONElua/AutoPlugin2#207]

**Comment by ONElua** [comment]
Wow...
Thanks

![2023-01-02-151528-066777](https://user-images.githubusercontent.com/25811032/210278715-356477de-921c-447a-98e0-a43898d5e226.png)

![2023-01-02-151550-649845](https://user-images.githubusercontent.com/25811032/210278726-7dbf9d1f-15ec-492c-8928-3bea93b6b497.png)
