### ISSUE TITLE
Add QuickMenuReborn and DolceWifi

### ISSUE THREAD

**Issue by LakiBR** [ONElua/AutoPlugin2#213]
These plugins can add enable/disable wireless connection on quick menu to PSTV users.

**Comment by ONElua** [comment]
please test
https://www.dropbox.com/s/284xjbbmqnww200/AutoPlugin2.vpk?dl=0

and send me screenshoot for dolcewifi

**Comment by LakiBR** [comment]
Tested. It's working properly. Follow the screenshots:

![1](https://user-images.githubusercontent.com/104247989/228971077-215d9bcc-f883-4f7c-ae8b-5ae887593d9b.jpg)
![2](https://user-images.githubusercontent.com/104247989/228971096-b1b2614a-69fc-48e9-b478-6e4d3c1e794c.jpg)
![3](https://user-images.githubusercontent.com/104247989/228971113-93d5f38f-5df1-4fe5-9a56-2b8329c76646.jpg)
![4](https://user-images.githubusercontent.com/104247989/228971133-4a542dcb-b42e-4e3a-a4a4-e817cc6c6200.jpg)

**Comment by ONElua** [comment]
DolceWiFi only works on vita tv

Thanks for quickly testing.

**Comment by ONElua** [comment]
Wait for the official update Next days
