### ISSUE TITLE
Update VolLightbarCtrlWithDS4

### ISSUE THREAD

**Issue by LakiBR** [ONElua/AutoPlugin2#214]
Update the plugin to add the function to control lightbar of DS4 on VITA/PSTV.

**Comment by ONElua** [comment]
Can you take a screenshot from this plugin?

**Comment by LakiBR** [comment]
On the PSTV/Vita there's no interface for the lightbar, cause it's only change the colors/control brightness on the controller itself. I can send you some pics later if you want.

For the volume control there's an interface. Follow the screenshots:

Volume up:

![1](https://user-images.githubusercontent.com/104247989/228972758-5d023ff5-8c95-438e-81b4-d73ef8333938.jpg)

Volume down:

![2](https://user-images.githubusercontent.com/104247989/228972801-5229b429-44c8-4484-b837-1de8aaa47f0d.jpg)

Mute:

![3](https://user-images.githubusercontent.com/104247989/228972823-530090f8-5db7-47e0-a85d-2adf7d9e0fda.jpg)

Thanks! :)

**Comment by ONElua** [comment]
Ok
