### ISSUE TITLE
option to configure Vita Nearest Neighbor plugin Removed?

### ISSUE THREAD

**Issue by LittleHooligan74** [ONElua/AutoPlugin2#217]
I updated auto plugin 2 1.23 to the version and the Nearest Neighbor setting doesn't appear on the menu even when searching for it
![2023-05-114627](https://user-images.githubusercontent.com/93485120/230183001-65c51882-366e-4865-a0a1-6cf71ca72d78.png)
![2023-04-05-114627](https://user-images.githubusercontent.com/93485120/230183004-cfcbce58-1c86-497b-aa45-e686e3f70d33.png)

**Comment by ONElua** [comment]
It's true
soon will be again
