### ISSUE TITLE
кнопка "удалить" вместо "установить"

### ISSUE THREAD

**Issue by lilPrince** [ONElua/AutoPlugin2#235]
В русской локализации, при установке плагина внизу слева кнопка "удалить" (по кнопке "X"), а должна быть "установить"

**Comment by ONElua** [comment]
Screenshot please

**Comment by lilPrince** [comment]
![2023-06-29-170204](https://github.com/ONElua/AutoPlugin2/assets/5466520/c0f80158-5822-4fb5-b4f6-8dc6ae34a4fa)
