### ISSUE TITLE
2.06 missing features??

### ISSUE THREAD

**Issue by ralphieb2t** [ONElua/AutoPlugin2#242]
I upgraded my Autoplugin 2 to 2.06 recently & it seems like it’s missing a bunch of options now. There used to be an option for itls, to set a custom backsplash or warning label and a few other helpful options. Are they located somewhere else in the new version? Or were they removed for some reason?

**Comment by ONElua** [comment]
![2023-07-16-220227-950677](https://github.com/ONElua/AutoPlugin2/assets/25811032/622d77b4-efc5-42a0-af93-4c2f7c74b027)
![2023-07-16-220312-075807](https://github.com/ONElua/AutoPlugin2/assets/25811032/935fde24-6c19-4c9c-9fd5-f20370468918)
![2023-07-16-220321-035119](https://github.com/ONElua/AutoPlugin2/assets/25811032/cdd52a87-897a-4866-a1ed-d12ca205f8df)

**Comment by ralphieb2t** [comment]
> ![2023-07-16-220227-950677](https://user-images.githubusercontent.com/25811032/253851174-622d77b4-efc5-42a0-af93-4c2f7c74b027.png) Extras-Download ![2023-07-16-220312-075807](https://user-images.githubusercontent.com/25811032/253851181-935fde24-6c19-4c9c-9fd5-f20370468918.png) Personalize (triangle)
> 
> ![2023-07-16-220321-035119](https://user-images.githubusercontent.com/25811032/253851188-cdd52a87-897a-4866-a1ed-d12ca205f8df.png) Personalize (triangle)

Thanks so much! Couldn’t find these sneaky little options. I guess I’ll just close this up then; hopefully anyone else having trouble finding these will
