### ISSUE TITLE
AutoPlugin II downloading plugins against my will after installing plugin updates

### ISSUE THREAD

**Issue by Windows10User2** [ONElua/AutoPlugin2#246]
After running AutoPlugin II and it detecting and installing plugin updates, plugins regarding Catherine: Full Body, Persona 4 Golden (two of them) and Vita Nearest Neighbour appeared out of nowhere in "ur0:tai/plugins" even though they're not set in the config.txt file. I deleted them but after running AutoPlugin II again and it detecting and installing plugin updates once more, the plugins regarding Catherine: Full Body, Persona 4 Golden and Vita Nearest Neighbour reappeared out of nowhere in "ur0:tai/plugins" and I deleted them again. Maybe they always reappear after deleting them and AutoPlugin II detecting and installing plugin updates.

**Comment by ONElua** [comment]
Send me your config.txt

**Comment by ONElua** [comment]
FIX https://github.com/ONElua/AutoPlugin2/commit/defbfe5675bda2a0f89f2842cc10dcb0d3a126c2

**Comment by Windows10User2** [comment]
> Its true

Will you fix this issue?

**Comment by ONElua** [comment]
Yes...
Next update

**Comment by Windows10User2** [comment]
> Yes... Next update

I just noticed plugons removed by AutoPlugin II aren't deleted from the folder even though their line is removed from the config.txt file.

**Comment by ONElua** [comment]
@Windows10User2 Its normal

**Comment by Windows10User2** [comment]
> @Windows10User2 Its normal

Why? Could you make it remove them besides their lines in config.text?
