### ISSUE TITLE
(new plugin addment) rinCheat plugin by Rinnegatamante

### ISSUE THREAD

**Issue by Thetouchedjoe** [ONElua/AutoPlugin2#252]
link for the plugin = https://github.com/Rinnegatamante/rinCheat

and by the way, do you agree to add a new plugin to AutoPlugin2 ?

**Comment by ONElua** [comment]
Which plugin?

**Comment by Thetouchedjoe** [comment]
the latest version of the rinCheat which is on rinCheat beta4 with debug features 
LINK : https://github.com/Rinnegatamante/rinCheat/releases/tag/beta4_debug

Here's the link for the latest version for rinCheat

**Comment by ONElua** [comment]
Old plugin was only for testing
