### ISSUE TITLE
( Plugin Request ) LittleBigPlanet Custom server plugins (Allefresher)

### ISSUE THREAD

**Issue by Beyley** [ONElua/AutoPlugin2#261]
[Allefresher](https://github.com/LittleBigRefresh/Allefresher) is a CFW game plugin for PSP/Vita that i have been working on which live patches LBP Vita and LBP PSP at runtime to connect to custom servers, replacing the online connectivity lost after the LBP PSP servers shut down in 2016, and the LBP Vita servers shut down in 2021.

It comes in two plugins, `Allefresher_vita.suprx` (a Vita CFW plugin for LBP Vita), and `Allefresher.prx` (a PSP CFW plugin for LBP PSP, which also works in Adrenaline). The current release versions of each plugin can be found [here](https://github.com/LittleBigRefresh/Allefresher/releases/tag/v1.0.0).

The PSP plugin has no plugin dependencies, while the Vita plugin *requires* iTLS to be installed, and the user to be running ensou CFW, so it needs to be marked as a hard dependency.

The PSP plugin requires some extra setup, where two files `Allefresher_format.txt` and `Allefresher_domain.txt` need to be placed inside of the `SEPLUGINS` folder (see the README). The Vita plugin does not require this.

The default contents of the `Allefresher_format.txt` file should be
```
http://%s:2095/lbp%s
```
And the default contents of the `Allefresher_domain.txt` file should be 
```
refresh.jvyden.xyz
```

It should also be noted that the user must have their game updated to the latest release (LBP PSP `2.0.5`, LBP Vita `1.22`). Ideally AutoPlugin would check for this, but if not possible, it can just be noted down in the plugin's page. It also needs to be noted down that an account must be created on the site `https://lbp.littlebigrefresh.com/` for the custom servers to allow the user to connect. This site doesnt currently work in the Vita web browser, so a phone or computer must be used.

I attempted to add this myself, but my Lua knowledge is very little, so i wasnt able to do this in a way which felt sane to the existing codebase. I mostly struggled with the fact that Allefresher_vita is a game plugin, and LBP Vita has a large amount of title IDs (see [here](https://github.com/LittleBigRefresh/Refresh/blob/ed9d031f486d43d4e5acd43429f39b21e8bb89f4/Refresh.GameServer/Authentication/TokenGameUtility.cs#L85) for our current known list of title IDs). I couldnt figure out a way in the existing `autoplugin.lua` script to install a plugin for *multiple* title IDs at once, or to have an option for which to install to (i personally have 3 copies of the game i switch between to test things). I also couldnt figure out a way to determine game version and block installation if the game version is incorrect.

**Comment by ONElua** [comment]
http://%s:2095/lbp%s

How is it obtained ?

**Comment by Beyley** [comment]
> http://%s:2095/lbp%s
> 
> How is it obtained ?

In LBP PSP, game server requests are formatted into a buffer using that string as the format string, the official one is like `http://%s:10060/LITTLEBIGPLANETPSP_XML%s`, and i modified that to use port `2095` (what our gameserver uses)` and to shorten the path from `LITTLEBIGPLANETPSP_XML` to just `lbp`

the PSP `Allefresher.prx` plugin finds the original format string in the game, and patches that to the format string in the text file

**Comment by ONElua** [comment]
please try

https://www.dropbox.com/scl/fi/vinzcbqcflr1nhewx9im0/AutoPlugin2.vpk?rlkey=p2ublekt00tih9opkg6nwtsdz&st=cq8qkpqm&dl=0

Vita plugins-> Hd Patches and DLC unlocker -> LBP Custom Server

**Comment by Beyley** [comment]
This seems to work great for LBP Vita, although there is a minor UI bug in the menu, where the title IDs use the wrong text, using the current title ID instead of the option's title ID

https://github.com/ONElua/AutoPlugin2/assets/34501060/cf9382bc-9be3-4657-afbb-96d8653b208c

**Comment by ONElua** [comment]
https://www.dropbox.com/scl/fi/fskjx0q7cq4fv3zl3z4oc/lbp.lua?rlkey=5rjuz2mrgmqbg8zi0z3b0lgvn&st=t8w4q6jv&dl=0

replace in
AUTOPLUG2\scripts\psvita

**Comment by Beyley** [comment]
yup, that fixes the UI issues, and the version check works aswell

**Comment by ONElua** [comment]
This is for all ?

And the default contents of the Allefresher_domain.txt file should be

refresh.jvyden.xyz

**Comment by Beyley** [comment]
> This is for all ?
> 
> And the default contents of the Allefresher_domain.txt file should be
> 
> refresh.jvyden.xyz

yes, thats the default contents of `Allefresher_domain.txt`. the default contents of `Allefresher_format.txt` should be `http://%s:2095/lbp%s`. Both files should be present in the `pspemu/SEPLUGINS` folder
This is only required for the PSP plugin to be clear

**Comment by ONElua** [comment]
for psp
https://www.dropbox.com/scl/fi/vinzcbqcflr1nhewx9im0/AutoPlugin2.vpk?rlkey=p2ublekt00tih9opkg6nwtsdz&st=xw0nj3mn&dl=0

**Comment by Beyley** [comment]
that seems to work great for PSP

**Comment by ONElua** [comment]
Thanks
https://github.com/ONElua/AutoPlugin2/releases/tag/2.11
