### ISSUE TITLE
please update https://silica.codes/Li/makepsmgreatagain/

### ISSUE THREAD

**Issue by LiEnby** [ONElua/AutoPlugin2#276]
its a small change to make activever.dat set to 2.00 by default instead of 1.21, which seems to kpanic)

also maybe a better description of the thing like 'fixes publisher license in psm developer assistant' .. or something like that, i dont know. hah.

**Comment by ONElua** [comment]
thanks°!!!
https://github.com/ONElua/AutoPlugin2/commit/0cae81e556ec7206ddded29bffbe2020c3b252d9
