### ISSUE TITLE
noPsmWhitelist

### ISSUE THREAD

**Issue by ZweiBR** [ONElua/AutoPlugin2#29]
Missing plugin (noPsmWhitelist) for games on PSTV that doesn't work
ur0:tai/noPsmWhitelist.skprx

example games
Mortal Kombat 9
Uncharted: Golden Abyss

https://bitbucket.org/SilicaAndPina/nopsmwhitelist/src/master/
https://bitbucket.org/SilicaAndPina/nopsmwhitelist/downloads/

**Comment by ZweiBR** [comment]
https://mega.nz/#!T4QQDCqQ!VEigVNbtD4pXsMQL5mDNbyaBlZkguvfflSM_sFg1j0E

**Comment by ONElua** [comment]
try with Dolcepolce

**Comment by ZweiBR** [comment]
interesting
hadn't seen this plugin

Is this Dolcepolce plugin better than noPsmWhitelist?

**Comment by ZweiBR** [comment]
yes
