### ISSUE TITLE
script.lua wrong code?

### ISSUE THREAD

**Issue by ChazW** [ONElua/AutoPlugin2#41]
When I first auto updated from autoplugin and try to launch autoplugin 2 it sent me straight to onedebugger with message 57, script.lua, attempt to call global message wait. I then delete the script.lua in app/AUTOPLUGIN2 and redownloaded it from this git, now it shows 7 unexpect symbol near <

**Comment by ChazW** [comment]
so the line 57 is because my system language is set to Chinese

**Comment by ChazW** [comment]
and the line 7 is because i didnt download the correct script.lua file even though i save the link from github using chrome

**Comment by ONElua** [comment]
please
install
https://github.com/ONElua/AutoPlugin2/releases/tag/1.03

**Comment by BaltazaR4** [comment]
Same as issue #11 Try changing system language to english and then open Autoplugin2 go to its settings, select change language, then select chinese and Autoplugin2 will download a pgf font file and thats it.
