### ISSUE TITLE
Got error on start

### ISSUE THREAD

**Issue by CarterLi** [ONElua/AutoPlugin2#42]
![15865717852482823521723103014161](https://user-images.githubusercontent.com/6134068/79033162-7db21380-7bde-11ea-91c2-c5b1a3a9828b.jpg)

script.lua
57
attempt to call 'message_wait' (a nil value)

**Comment by yexun1995** [comment]
#41

**Comment by CarterLi** [comment]
> #41

I did install 1.3

**Comment by ONElua** [comment]
chinese?

**Comment by BaltazaR4** [comment]
This is same situation as issue #11 Try changing to english and then open Autoplugin2 go to its settings, select change language, then select chinese and Autoplugin2 will download a pgf font file and thats it.

**Comment by CarterLi** [comment]
> This is same situation as issue #11 Try changing system language to english and then open Autoplugin2 go to its settings, select change language, then select chinese and Autoplugin2 will download a pgf font file and thats it.

It works. Thanks

**Comment by DevDavisNunez** [comment]
@CarterLi @yexun1995 We are working on a direct solution,
Can you try this VPK(rename to vpk from zip)?
To try deleting the ux0: / data / Autoplugin2 folder, install this vpk, and start normally.
[AutoPlugin2.zip](https://github.com/ONElua/AutoPlugin2/files/4467197/AutoPlugin2.zip)

**Comment by CarterLi** [comment]
It works for me @DevDavisNunez

**Comment by DevDavisNunez** [comment]
Thanks for your test @CarterLi, 
New [release 1.04](https://github.com/ONElua/AutoPlugin2/releases/tag/1.04) fix this issue.
