### ISSUE TITLE
Psvita shuts down after installing henkaku (last thing i did was to update Autoplugin 2 to 1.04)

### ISSUE THREAD

**Issue by NeroTheYoung** [ONElua/AutoPlugin2#46]
As i said in the title, the last thing i did was to update Autoplugin2 to 1.04 and inside it i installed the plugins that i had before in ux0 (except psVshell), my psvita is at 3.60.

**Comment by NeroTheYoung** [comment]
https://www.reddit.com/r/vitahacks/comments/g1vowq/do_not_use_autoplugin_2_latest_version/ 



Thanks to Cimmerian_Iter

**Comment by NeroTheYoung** [comment]
https://www.reddit.com/r/vitahacks/comments/g1vowq/do_not_use_autoplugin_2_latest_version/ 

Thanks to Cimmerian_Iter

**Comment by DevDavisNunez** [comment]
@NeroTheYoung Please update to 1.05 and use "Reset config.txt in ur0:tai" in the section Extras and reinstall all your plugs, sorry for the problems caused by the bug.
