### ISSUE TITLE
HENKAKU SETTINGS DISSAPEAR WHEN LAUNCHING THE APPLICATION OR INSTALLING ANY PLUGIN

### ISSUE THREAD

**Issue by barbabrilios825** [ONElua/AutoPlugin2#52]
As the title says henkaku settings disappeare every time I install any plugin.Also I tried it on 3.65 and 3.60 and same thing please fix it as soon as possible I cant acces psn.

**Comment by theheroGAC** [comment]
use version 1.05 please,reset your ur0 and reinstall all plugin
