### ISSUE TITLE
Problem with new update?

### ISSUE THREAD

**Issue by DiegooBedin** [ONElua/AutoPlugin2#65]
I don't know if this is actually a problem, but vita's behavior is strange.

In the tab of installed plugins of AutoPluginII henkaku.suprx is appearing in yellow and with the index saying "must have plugin, can not unistall" ..

I don't know what that means, I already tried the procedure to reload config.txt, reinstalled enso (3.60), but even without other plugins it appears ..

I switched back to Autoplugin I and the henkaku plugin does not appear as installed there.

This started to happen when I installed the new AutoPluginII update and since then, sometime later with any game open it locks the system and shuts down ..

Any relation to the new update? any solution with this by the application or related to the update?

**Comment by BaltazaR4** [comment]
Its not an issue, "must have plugin, can not uninstall" means this plugin must be in your ur0:tai folder and enabled at config.txt and uninstalling is not allowed.
And about the system locking itself and powering off, can you tell which plugins you have installed when happened? So we can test for compatibility.

**Comment by DiegooBedin** [comment]
None. In fact, after updating AutoPluginII to the latest version, I uninstalled LowMemMode which for some reason did not work on my vita ..

Since then, even restoring the system, it continues to crash in games or at system boot.

I needed to upgrade to 3.73 and downgrade to 3.60 to get back to a stable system.

P.S.: I also have "custom boot splash" and "custom warning" enabled, maybe they are?

**Comment by BaltazaR4** [comment]
Custom boot and splash should not give you conflict, we check that out  a few versions ago (conflict with udcd full version), unless you install them with autoplugin, can you upload a pic of whats written to your config.txt under kernel please?

**Comment by DiegooBedin** [comment]
I can not post because I already did the process I mentioned above to have 3.60 again without bugs, I have an old back up when all plugins worked ok until you install the custom boot splash ..

But some time ago I had up to 15 plugins plus reFood, Repatch, NoNPDrm, Adrenaline, the most common ones

Well, I installed the custom boot splash and the custom warning plugins using the autoplugin and did not have the ucdc installed. Should I install it manually? And where to place the custombootsplash? in the boot_config.txt config or in the config.txt?
Usually placed in config.txt just below henkaku.skprx and memory.skprx

On the issue of conflict, I have a few questions:
How many plugins can I install on vita? I am interested in several of them, but installing them all will probably make the vita crash, I'm afraid.


So was my config.txt that worked antes do custombootsplash:

# This file is used as an alternative if ux0: tai / config.txt is not found.
# For users plugins, you must refresh taiHEN from HENkaku Settings for
# changes to take place.
# For kernel plugins, you must reboot for changes to take place.
* KERNEL
ur0: tai / henkaku.skprx
ur0: tai / memory.skprx
ux0: app / pspemucfw / sce_module / adrenaline_kernel.skprx
ur0: tai / analogsenhancer.skprx
ur0: tai / nonpdrm.skprx
ur0: tai / ref00d.skprx
ur0: tai / repatch.skprx
ur0: tai / vitabright.skprx
ur0: tai / itls.skprx
ur0: tai / lolicon.skprx
ur0: tai / nopsmdrm.skprx
ur0: tai / ioplus.skprx
ur0: tai / ds4vita.skprx
ur0: tai / udcd_uvc_oled_off.skprx
ur0: tai / vitacheat360.skprx
ur0: tai / itls.skprx
ur0: tai / dsmotion.skprx
ur0: tai / psonescrot.skprx
# henkaku.skprx is hard-coded to load and is not listed here
* main
ur0: tai / download_enabler.suprx
ur0: tai / pngshot.suprx
ur0: tai / QAscreenshot.suprx
ur0: tai / quick_power.suprx
ur0: tai / quick_volume.suprx
ur0: tai / shellsecbat.suprx
ur0: tai / LowMemMode.suprx
# main is a special titleid for SceShell
ur0: tai / henkaku.suprx
* NPXS10015
# this is for modifying the version string
ur0: tai / henkaku.suprx
* NPXS10016
# this is for modifying the version string in settings widget
ur0: tai / henkaku.suprx
# ITLS
* ALL
ur0: tai / TouchRemap.suprx
ur0: tai / InfiniteNet.suprx
ur0: tai / VitaGrafix.suprx
ur0: tai / dsmotion.suprx
* NPXS10036
ur0: tai / reScreeny.suprx
* NPXS10013
ur0: tai / ps4linkcontrols.suprx

# ITLS

**Comment by DiegooBedin** [comment]
I can not post because I already did the process I mentioned above to have 3.60 again without bugs, I have an old back up when all plugins worked ok until you install the custombootsplash ..

But some time ago I had up to 15 plugins plus reFood, Repatch, NoNPDrm, Adrenaline, the most common ones

Well, I installed the custom boot splash and the custom warning plugins using the autoplugin and did not have the ucdc installed. Should I install it manually? And where to place the custombootsplash? in the boot_config.txt config or in the config.txt?
Usually placed in config.txt just below henkaku.skprx and memory.skprx

On the issue of conflict, I have a few questions:
How many plugins can I install on vita? I am interested in several of them, but installing them all will probably make the vita crash, I'm afraid.

So was my config.txt that worked antes do custombootsplash:
I removed the #

"This file is used as an alternative if ux0: tai / config.txt is not found.
For users plugins, you must refresh taiHEN from HENkaku Settings for
changes to take place.
For kernel plugins, you must reboot for changes to take place.
KERNEL
ur0: tai / henkaku.skprx
ur0: tai / memory.skprx
ux0: app / pspemucfw / sce_module / adrenaline_kernel.skprx
ur0: tai / analogsenhancer.skprx
ur0: tai / nonpdrm.skprx
ur0: tai / ref00d.skprx
ur0: tai / repatch.skprx
ur0: tai / vitabright.skprx
ur0: tai / itls.skprx
ur0: tai / lolicon.skprx
ur0: tai / nopsmdrm.skprx
ur0: tai / ioplus.skprx
ur0: tai / ds4vita.skprx
ur0: tai / udcd_uvc_oled_off.skprx
ur0: tai / vitacheat360.skprx
ur0: tai / itls.skprx
ur0: tai / dsmotion.skprx
ur0: tai / psonescrot.skprx
henkaku.skprx is hard-coded to load and is not listed here
main
ur0: tai / download_enabler.suprx
ur0: tai / pngshot.suprx
ur0: tai / QAscreenshot.suprx
ur0: tai / quick_power.suprx
ur0: tai / quick_volume.suprx
ur0: tai / shellsecbat.suprx
ur0: tai / LowMemMode.suprx
main is a special titleid for SceShell
ur0: tai / henkaku.suprx

NPXS10015
this is for modifying the version string
ur0: tai / henkaku.suprx

NPXS10016
this is for modifying the version string in settings widget
ur0: tai / henkaku.suprx

ITLS
ALL
ur0: tai / TouchRemap.suprx
ur0: tai / InfiniteNet.suprx
ur0: tai / VitaGrafix.suprx
ur0: tai / dsmotion.suprx
NPXS10036
ur0: tai / reScreeny.suprx
NPXS10013
ur0: tai / ps4linkcontrols.suprx
ITLS"

**Comment by vaass95** [comment]
I'm having almost the same problem, but it says"must have plugin can not uninstall" and a line under it it says "the plugin is missing!". It modified my config and added some text lines ("NPXS10015-16") that I didnt have before, I'm a little consufed tbh.

**Comment by ONElua** [comment]
> I'm having almost the same problem, but it says"must have plugin can not uninstall" and a line under it it says "the plugin is missing!". It modified my config and added some text lines ("NPXS10015-16") that I didnt have before, I'm a little consufed tbh. Btw I have Henkaku.suprx located in vs0:/tai.

boot_config.txt exists in vs0:tai/  ???

**Comment by ONElua** [comment]
> I can not post because I already did the process I mentioned above to have 3.60 again without bugs, I have an old back up when all plugins worked ok until you install the custombootsplash ..
> 
> Well, I installed the custom boot splash and the custom warning plugins using the autoplugin and did not have the ucdc installed. Should I install it manually? And where to place the custombootsplash? in the boot_config.txt config or in the config.txt?

https://github.com/Princess-of-Sleeping/PSP2-CustomBootSplash


memory.skprx 
you have no original memory?

# henkaku.skprx is hard-coded to load and is not listed here

should not be activated !!!!

**Comment by ONElua** [comment]
The lines that we show about henkaku.suprx are only informative, these plugins are essential to have henkaku settings, so they should not be uninstalled.
All config.txt must have these lines

https://github.com/TheOfficialFloW/h-encore/blob/master/bootstrap/bootstrap.c#L33

**Comment by DiegooBedin** [comment]
> boot_config.txt existe em vs0: tai / ???

This is now for me too


I tried last night for experience installing all these plugins that were in the old config.txt that I mentioned above, leaving out only custombootsplash and customwarning, and it was ok, including the boot that used to crash sometimes ..

Today I woke up with the disconnection message from Sony's proprietary card, however, the FW works perfectly, but I thought that the crashes in play could be related to this disconnection .. they think it is a related problem, or incompatibility of customwarning or custombootsplah with some another plugin ??

**Comment by DiegooBedin** [comment]
>memory.skprx
>you have no original memory?

This plugin comes from installing sd2vita by Mlthaku

**Comment by ONElua** [comment]
but you don't have original memory ?

**Comment by DiegooBedin** [comment]
I don't know exactly what you mean by that. I have a PsVita 1000 (OLED) that has no internal memory, and I have a Sony proprietary memory card.
but the "memory.suprx" plugin is to activate SD2vita, if you remove it sd2vita does not work

**Comment by ONElua** [comment]
> I don't know exactly what you mean by that. I have a PsVita 1000 (OLED) that has no internal memory, and I have a Sony proprietary memory card.
> but the "memory.skprx" plugin is to activate SD2vita, if you remove it sd2vita does not work

why don't you use storagemgr for your sd2vita and memory card

**Comment by DiegooBedin** [comment]
> why don't you use storagemgr for your sd2vita and memory card

I didn't use it because I was used to Mlthaku, but I installed it now and although it takes about 3 times longer to boot the system, it works, so I'll join the use.

I think I found the problem, I installed all the plugins again, those mentioned in config.txt, including custom_boot_splash and custom_warning, and the boot only crashes now if I include udcd_uvc OLED, otherwise it is working perfectly. So, maybe there are still conflict between udcd_uvc and some other plugin ..

**Comment by ONElua** [comment]
please show me config

**Comment by DiegooBedin** [comment]
I tried to install more plugins that I had the least interest to test the limit .. 

custom_boot_splash.suprx are installed in boot_config.txt


This is config.txt sem os #

"This file is used as an alternative if ux0:tai/config.txt is not found.
 For users plugins, you must refresh taiHEN from HENkaku Settings for
 changes to take place.
 For kernel plugins, you must reboot for changes to take place.
*KERNEL
ur0:tai/storagemgr.skprx
ur0:tai/reF00D.skprx
ur0:tai/repatch.skprx
ux0:app/pspemucfw/sce_module/adrenaline_kernel.skprx
ur0:/tai/analogsenhancer.skprx
ur0:/tai/nonpdrm_un.skprx
ur0:/tai/nopsmdrm.skprx
ur0:/tai/ds4vita.skprx
ur0:/tai/dsmotion.skprx
ur0:/tai/lolicon.skprx
ur0:/tai/psonescrot.skprx
ur0:/tai/vitabright.skprx
ur0:/tai/vitacheat360.skprx
ur0:/tai/ioplus.skprx
ur0:tai/itls.skprx
ur0:/tai/music_premium.skprx
henkaku.skprx is hard-coded to load and is not listed here
*main
main is a special titleid for SceShell
ur0:tai/henkaku.suprx
ur0:tai/custom_warning.suprx
ur0:/tai/download_enabler.suprx
ur0:/tai/shellsecbat.suprx
ur0:/tai/pngshot.suprx
ur0:/tai/quick_power.suprx
ur0:/tai/quick_volume.suprx
ur0:/tai/LowMemMode.suprx
ur0:/tai/QAscreenshot.suprx
*NPXS10015
this is for modifying the version string
ur0:tai/henkaku.suprx
*NPXS10016
this is for modifying the version string in settings widget
ur0:tai/henkaku.suprx
*ALL
ur0:tai/TouchRemap.suprx
ur0:/tai/dsmotion.suprx
ur0:/tai/InfiniteNet.suprx
ur0:/tai/VitaGrafix.suprx
*NPXS10036
ur0:/tai/reScreeny.suprx
ITLS
*NPXS10013
ur0:/tai/ps4linkcontrols.suprx"

**Comment by ONElua** [comment]
ok
close

**Comment by vaass95** [comment]
> > I'm having almost the same problem, but it says"must have plugin can not uninstall" and a line under it it says "the plugin is missing!". It modified my config and added some text lines ("NPXS10015-16") that I didnt have before, I'm a little consufed tbh. Btw I have Henkaku.suprx located in vs0:/tai.
> 
> boot_config.txt exists in vs0:tai/ ???

yes it does.
