### ISSUE TITLE
bootsound doesn't install properly

### ISSUE THREAD

**Issue by doctorwhosthat** [ONElua/AutoPlugin2#72]
- doesn't download "bootsound.surpx" file:
https://github.com/teakhanirons/Vita-BootSound/releases/download/1.0/bootsound.suprx
- doesn't edit config.txt properly to add required code string to use plugin
```
*main
ur0:tai/bootsound.suprx
```
shows instead
```
*main
ur0:tai/bootsound
```

**Comment by ONElua** [comment]
ok
im fix in the next update
for the plugins.lua


Thanks for the report.

**Comment by ONElua** [comment]
Fix https://github.com/ONElua/AutoPlugin2/commit/06b4573b09281bd839710fe7b6dc2258d150b010
Please Plugins Update in AutoPlugin2

**Comment by doctorwhosthat** [comment]
Thank for looking into this issue. 👍
