### ISSUE TITLE
Plugin updater not working

### ISSUE THREAD

**Issue by tatundria** [ONElua/AutoPlugin2#73]
Whenever I try to update the plugins through plugins updater I get the following error:

plugins_online.lua
265
bad argument #1 to 'lower' (string expected, got nil)

**Comment by ONElua** [comment]
Thanks
New release soon
https://github.com/ONElua/AutoPlugin2/commit/46dd50e2dc32d313a555f42a2b8037c422587625
So 
Please use download available languages

**Comment by ONElua** [comment]
is working in v1.09 ??

**Comment by tatundria** [comment]
> is working in v1.09 ??

Yes it is
