### ISSUE TITLE
Russian Translate

### ISSUE THREAD

**Issue by Yoti** [ONElua/AutoPlugin2#8]
Not just translated, but partially adopted Russian language for Autoplugin II.
I may maintain future changes as well. Tell me if I need to change text encoding.
[RUSSIAN.lua.txt](https://github.com/ONElua/AutoPlugin2/files/4281709/RUSSIAN.lua.txt)
[RUSSIAN.zip](https://github.com/ONElua/AutoPlugin2/files/4281713/RUSSIAN.zip)

**Comment by Yoti** [comment]
We also have a pull request with another translation. As I may see my translation skill is better. For example, this guy "translated" obvious mistype "ae" into some mystic "a.e.". Also, there are a lot of Capital Letters which aren't used in Russian language.

**Comment by ONElua** [comment]
im testing...  send a vpk for testing
