### ISSUE TITLE
[Suggestion] Background Music

### ISSUE THREAD

**Issue by bielgiroto** [ONElua/AutoPlugin2#84]
It would be nice having a little music on background while we setup our plugins/configure some of them, just like on the PS Store, idk.

I just like more of those store apps that have some nice and chill music on the background, I think that autoplugin could use of it.

(That's just a suggestion, the app works perfectly fine for me. I'll not get angry if this get closed or something, I understand that this an issues topic, not suggestions, but I'll appreciate if someday this gets added)

**Comment by ONElua** [comment]
Send your background music xD

**Comment by bielgiroto** [comment]
Oh for real? Didn't expected for a song request that quickly XD
Anyway, I think that this one could fit the autoplugin very well, it's very relaxing, and have some nice and smooth instrumental too;
Tell me what do you think though; I want to know if it's only me that thinks this song could work with the app
http://www.mediafire.com/file/zt0ma5vudyubjg8/file

**Comment by ONElua** [comment]
Copyright?

**Comment by bielgiroto** [comment]
OHHH SHIT THIS SONG HAS COPYRIGHT, SORRY!
I have another one here, and it's copyright free now! It's from "Kalaido", the name's "Hanging Lanterns"

Here's the song on youtube:
https://www.youtube.com/watch?v=xzXemfeXkZw&list=PL6k57M9aVcIIARkqPG06AapxZ99yqepds&index=3

Here you can download it.
http://www.mediafire.com/file/39ywqwwrb235byt/file

Sorry about that, I forgot to verify the Copyright stuff, please tell me what you think about that new song.

**Comment by bielgiroto** [comment]
Aaaah... Dude it's very relaxing updating my plugins while listening to this song...

Thank you so much!
