### ISSUE TITLE
French.lua error

### ISSUE THREAD

**Issue by g45t0n** [ONElua/AutoPlugin2#86]
![16003902244682074543091818429473](https://user-images.githubusercontent.com/5075445/93542604-72021000-f927-11ea-8a28-117d2afe06a9.jpg)
 Hi, I am getting this error when starting autoplugin after trying to update my plugins and it crashed.

Thanks.

**Comment by BaltazaR4** [comment]
Try changing the system language on your PS vita to english and after that update the plugins and languages then reset system lang to french and retry Autoplugin 2 in french lang again.

**Comment by ONElua** [comment]
works??

**Comment by rufotheone-fr** [comment]
Hello. I have the same issue and the workaround that BaltazaR4 gave doesn't do the job...

**Comment by ONElua** [comment]
ok...
reinstall AutoPlugin II v1.10 and check
new updates in languages and plugins
