### ISSUE TITLE
Sharpscale error

### ISSUE THREAD

**Issue by Neon99** [ONElua/AutoPlugin2#89]
When I install sharpscale and open autoplugin I get this error and it forced me to restart psvita.
![2020-09-26-205928](https://user-images.githubusercontent.com/65186438/94348374-e0d41d00-003b-11eb-8118-c2512a8725e5.jpg)

**Comment by BaltazaR4** [comment]
Do this happens everytime you open Autoplugin 2 after installing sharpscale? Cause it was supposed to do it just once after installing sharpscale plugin

**Comment by Neon99** [comment]
> Do this happens everytime you open Autoplugin 2 after installing sharpscale? Cause it was supposed to do it just once after installing sharpscale plugin

Sharpscale works correctly. This error always happens when I open autoplugin.

**Comment by ONElua** [comment]
Please sendme yours configs...in  ur0 and ux0

**Comment by Neon99** [comment]
> Please sendme yours configs...in ur0 and ux0

[config.txt](https://github.com/ONElua/AutoPlugin2/files/5288852/config.txt)
![2020-09-27-204131](https://user-images.githubusercontent.com/65186438/94373052-0710c000-0103-11eb-96f3-8cb269f823e8.jpg)
![2020-09-27-204222](https://user-images.githubusercontent.com/65186438/94373057-0aa44700-0103-11eb-8610-8cfe48a96629.jpg)

**Comment by ONElua** [comment]
Please try with this config 
https://www.dropbox.com/s/ug4nk7f4n9jayjq/config.txt?dl=0

**Comment by Neon99** [comment]
> Please try with this config
> https://www.dropbox.com/s/ug4nk7f4n9jayjq/config.txt?dl=0

Now it's fixed, thanks
