### ISSUE TITLE
Wrong chinese font path

### ISSUE THREAD

**Issue by Yoti** [ONElua/AutoPlugin2#9]
Program still using ux0:data/AUTOPLUGIN instead of ux0:data/AUTOPLUGIN**2**.

**Comment by ONElua** [comment]
Try
https://drive.google.com/file/d/1kSvkz4tNW-T4aBLOu9Fzsj0Z8PYpSpFM/view?usp=sharing

**Comment by Yoti** [comment]
Destination path is fixed.

New bug: this font is applies not only for Chinese, but for any other language.

Also, updated Russian translate is attached.
[RUSSIAN.zip](https://github.com/ONElua/AutoPlugin2/files/4292040/RUSSIAN.zip)
[RUSSIAN.lua.txt](https://github.com/ONElua/AutoPlugin2/files/4292041/RUSSIAN.lua.txt)
