### ISSUE TITLE
Unable to turn off background music

### ISSUE THREAD

**Issue by Lyubphim** [ONElua/AutoPlugin2#92]
It's fine if someone really likes to hear background music, a certain song, while getting plugins. Personally, I'm not really fond of it, I don't know if it's just me or it's the song that's a little..., but it would be really nice to have an option to turn it off. Love the app, by the way.

**Comment by bielgiroto** [comment]
Hey, I choosed the song that was added some days ago, sorry if you didn't liked it.

Do you think the song was bad? It doesn't fit with autoplugin? Please tell-me what you think about it, I want to know if I made a bad choice.

(I'm not from the development team tough, I just suggested the song to be used)

**Comment by Lyubphim** [comment]
Don't think you did a bad choice, I really can't say if it fits with autoplugin. Maybe it's just my personal taste. But it would be great to have the option to just turn it off, for people like me that prefer to manage their plugins silently and without having to turn the volume all the way down.

**Comment by Shadow322** [comment]
i really want to disable it as well

**Comment by Yoti** [comment]
+1
How to disable this shitty music?
I hate background music at all.

**Comment by ONElua** [comment]
ok

**Comment by ONElua** [comment]
[v1.13 ](https://github.com/ONElua/AutoPlugin2/releases/tag/1.13)
