### ISSUE TITLE
Polish translation got broken (missing letters)

### ISSUE THREAD

**Issue by rand92000** [ONElua/AutoPlugin2#96]
The letters like **Ą, Ć, Ę, Ł, Ń, Ó, Ś, Ź, Ż**, that are exclusive for a Polish alphabet, compared to English, got replaced by "**_**" symbol recently.
Please, fix it. :((
Thank you in advance. :))

**Comment by ONElua** [comment]
Try
https://github.com/ONElua/AutoPlugin2/blob/master/font/font.pgf

**Comment by ONElua** [comment]
Add PVF System (Font)
https://github.com/ONElua/AutoPlugin2/commit/0eb2e74824c7a70bb5c769b43214df267e666c83
