### ISSUE TITLE
How can I add Turkish Language ?

### ISSUE THREAD

**Issue by Feardarks** [ONElua/AutoPlugin2#97]
Hey I want to add the Turkish language if you guys give me a text file or something ( I'm new in Github sorry if I wrote something wrong)

**Comment by ONElua** [comment]
with notepad++ 

[TURKISH.zip](https://github.com/ONElua/AutoPlugin2/files/5436287/TURKISH.zip)

**Comment by BaltazaR4** [comment]
Feardarks please translate anything inside the quotes only

**Comment by ONElua** [comment]
I close the issue
When you have the file...
send me
