### ISSUE TITLE
Fix Sharpscale Config Crash

### ISSUE THREAD

**Issue by Codemonkey03** [ONElua/AutoPlugin2#99]
Since installing Sharpscale through Autoplugin2, whenever I open Autoplugin2 it displays a message "Fix Sharpscale Config Crash" and the app will reboot when I close it regardless if a new mod was added or any changes were made.

I tried to research this message but I'm not finding anything. What does it mean? I haven't noticed any abnormal behavior beside this message.

Found an issue previous to this one about the exact same issue but the solution didn't work and there is no explanation on what was done in editing the tai config file to make that fix work.

**Comment by ONElua** [comment]
Do this happens everytime you open Autoplugin 2?
Send your config

**Comment by Codemonkey03** [comment]
Everytime. My original config is:

And I followed along with the config posted in the closed thread that resolved the issue for another ticket and now it looks like this cleaned up:

Same issue though, get the message every time Autoplugin boots even though all my plugins are operating normally.
